# Generated by Django 4.1.7 on 2023-12-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_absent_company_department_employee_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('telephone', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('approve_status', models.BooleanField(default=False)),
                ('decline_status', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
