# Generated by Django 4.1.7 on 2023-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_allrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='12345678', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='setup_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(default='admin', max_length=500, unique=True),
        ),
    ]
