# Generated by Django 4.1.7 on 2023-12-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_creation_date_company_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
