# Generated by Django 4.1.7 on 2023-12-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_com_id_quote_com_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
