# Generated by Django 4.1.7 on 2023-12-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_department_com_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='com_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
