# Generated by Django 4.1.7 on 2023-12-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_allrequest_telephone1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=50000)),
                ('com_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacypolicy', models.CharField(max_length=50000)),
                ('com_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
