# Generated by Django 4.1.7 on 2023-12-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_terms_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='level0_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='level0_comm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='level0_reject',
            field=models.BooleanField(default=False),
        ),
    ]
