# Generated by Django 4.1.7 on 2023-12-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_company_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_setup_completed',
            field=models.BooleanField(default=True),
        ),
    ]
