# Generated by Django 4.1.4 on 2023-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_employee_employee_setup_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrequest',
            name='company_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='allrequest',
            name='telephone',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='allrequest',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
