# Generated by Django 4.1.7 on 2023-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_allrequest_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
