# Generated by Django 4.1.7 on 2024-01-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_employee_email_alter_employee_office_email'),
        ('app', '0015_feedbackmodel'),
    ]

    operations = [
    ]
