# Generated by Django 4.1.7 on 2024-01-02 08:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20240102_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(validators=[app.models.validate_dob]),
        ),
    ]
