# Generated by Django 4.1.7 on 2024-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('com_id', 'emp_id')},
        ),
    ]
