# Generated by Django 4.1.7 on 2024-01-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_employee_emp_id_alter_employee_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('text', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolved', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
