# Generated by Django 4.1.7 on 2024-01-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_companybackup'),
        ('app', '0019_support'),
    ]

    operations = [
    ]
