# Generated by Django 4.1.7 on 2024-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_0017_companybackup_0019_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
