# Generated by Django 4.1.7 on 2024-01-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_support_comment_support_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quotes',
            field=models.TextField(max_length=5000),
        ),
    ]
