# Generated by Django 4.1.7 on 2024-01-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_feedbackmodel_emp_id_alter_feedbackmodel_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='to_devs',
            field=models.BooleanField(default=False),
        ),
    ]
