# Generated by Django 4.1.7 on 2024-01-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_feedbackmodel_to_devs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='to_devs',
            field=models.BooleanField(default=True),
        ),
    ]
