# Generated by Django 4.1.7 on 2024-01-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_feedbackmodel_to_devs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='logo/'),
        ),
    ]
