# Generated by Django 4.1.7 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Full Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
