# Generated by Django 4.1.7 on 2024-01-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo',
            new_name='company_image',
        ),
    ]
