# Generated by Django 4.1.7 on 2024-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_company_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.ImageField(upload_to='company_image/'),
        ),
    ]
