# Generated by Django 4.1.7 on 2024-01-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_company_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_image',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='dummylogo.png', upload_to='images/'),
        ),
    ]
