# Generated by Django 4.1.7 on 2024-01-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_leaveapplication_status_and_more'),
        ('app', '0028_alter_company_company_image'),
    ]

    operations = [
    ]
