# Generated by Django 4.1.7 on 2024-01-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_20240109_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
